#!/usr/bin/env python3
"""Bake hud_web_ui/ into src/hud_web_assets.c.

The editor has to arrive with the engine. Asking a player to install a web
server, or to keep a folder of .js files next to their binary, is exactly the
friction this tool exists to remove -- so the UI is compiled in and the engine
serves it from memory.

The output is committed. That keeps the Windows and Linux builds free of any
new build-time dependency: nothing but a C compiler is needed to build ezQuake,
same as before. Run this after editing anything under hud_web_ui/, and run it
with --check in review to prove the committed file matches the source.
"""

import argparse
import hashlib
import pathlib
import sys

# Only what the browser actually loads. fixtures/ is test input and PRODUCT.md
# is documentation; neither belongs in a shipped binary.
SOURCES = [
    "index.html",
    "favicon.svg",
    "ui.css",
    "core/bridge.js",
    "core/geometry.js",
    "core/log.js",
    "core/model.js",
    "view/app.js",
    "view/debug.js",
]

# One entry per suffix in SOURCES. A new asset type must add its own here, and
# will fail loudly on the KeyError below rather than shipping as octet-stream.
CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
}

HEADER = """/* Generated by tools/embed_hud_web_ui.py -- do not edit.
 *
 * Source: hud_web_ui/ ({count} files, {total} bytes, sha256 {digest})
 * Regenerate with:  python3 tools/embed_hud_web_ui.py
 */

#include "quakedef.h"
#include "hud_web.h"

"""


def c_bytes(data):
    lines = []
    for start in range(0, len(data), 16):
        chunk = data[start:start + 16]
        lines.append("\t" + "".join("0x%02x," % b for b in chunk))
    return "\n".join(lines)


def generate(ui_dir):
    blobs = []
    digest = hashlib.sha256()
    total = 0

    for index, relative in enumerate(SOURCES):
        path = ui_dir / relative
        data = path.read_bytes()
        digest.update(relative.encode("utf-8"))
        digest.update(data)
        total += len(data)
        blobs.append((index, relative, data))

    out = [HEADER.format(count=len(blobs), total=total, digest=digest.hexdigest()[:16])]

    for index, relative, data in blobs:
        out.append("/* /%s */\nstatic const unsigned char hud_web_asset_%d[] = {\n%s\n};\n\n"
                   % (relative, index, c_bytes(data)))

    out.append("static const struct {\n"
               "\tconst char *path;\n"
               "\tconst char *content_type;\n"
               "\tconst unsigned char *data;\n"
               "\tsize_t length;\n"
               "} hud_web_asset_table[] = {\n")
    for index, relative, data in blobs:
        out.append('\t{ "/%s", "%s", hud_web_asset_%d, %d },\n'
                   % (relative, CONTENT_TYPES[pathlib.Path(relative).suffix], index, len(data)))
    out.append("};\n\n")

    # Exact match only: no directory walking, no traversal to worry about, and a
    # typo in a path is a 404 rather than a silently different file.
    out.append("""const unsigned char *HUD_Web_Asset(const char *path, size_t path_length,
		const char **content_type, size_t *length)
{
	size_t i;

	/* The editor is what "/" means; there is nothing else to serve there. */
	if (path_length == 1 && path[0] == '/') {
		path = "/index.html";
		path_length = 11;
	}

	for (i = 0; i < sizeof(hud_web_asset_table) / sizeof(hud_web_asset_table[0]); i++) {
		if (strlen(hud_web_asset_table[i].path) == path_length &&
			!memcmp(hud_web_asset_table[i].path, path, path_length)) {
			*content_type = hud_web_asset_table[i].content_type;
			*length = hud_web_asset_table[i].length;
			return hud_web_asset_table[i].data;
		}
	}
	return NULL;
}
""")
    return "".join(out), total


def locate():
    """Find hud_web_ui/ and where the generated file belongs.

    One copy of this script serves two layouts: `tools/` beside `hud_web_ui/` and
    `src/` in an ezQuake checkout, and `engine/tools/` in the ez-hud repository,
    where `hud_web_ui/` sits at the root and the engine files live under `engine/`.
    Search upward for the UI rather than assuming a fixed depth, so neither repo
    needs its own edited copy to drift from the other.
    """
    here = pathlib.Path(__file__).resolve()
    for base in here.parents:
        ui = base / "hud_web_ui"
        if not ui.is_dir():
            continue
        for src in (base / "src", base / "engine" / "src"):
            if src.is_dir():
                return ui, src / "hud_web_assets.c"
        raise SystemExit(
            "found %s but no src/ or engine/src/ beside it" % ui)
    raise SystemExit("cannot locate hud_web_ui/ above %s" % here)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed file is stale instead of rewriting it")
    args = parser.parse_args()

    ui_dir, target = locate()
    generated, total = generate(ui_dir)

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != generated:
            sys.stderr.write(
                "%s is stale -- regenerate it with:\n  python3 %s\n"
                % (target, pathlib.Path(__file__).resolve()))
            return 1
        print("%s is up to date" % target)
        return 0

    target.write_text(generated, encoding="utf-8")
    print("wrote %s (%d bytes of UI)" % (target, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
