// tools/qa/gen_master_cfg.mjs — the master input cfg, and its coverage gate.
//
//   node tools/qa/gen_master_cfg.mjs <state.json|bridge-url> [--out file]
//   node tools/qa/gen_master_cfg.mjs <state.json|bridge-url> --check <file>
//
// One cfg that touches every registered element while keeping it inside the
// reference frame: every element is placed directly against the screen,
// alignments cycle deterministically, and offsets always point inward from the
// selected edge. The --check mode fails when the engine registers an element
// the cfg does not cover — coverage can never silently rot (plan B1).

import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';

const ALIGN_X = ['left', 'center', 'right'];
const ALIGN_Y = ['top', 'center', 'bottom'];

function inset(align, index) {
	const amount = 8 * (1 + (index % 3));
	if (align === 'right' || align === 'bottom') return -amount;
	if (align === 'center') return 0;
	return amount;
}

async function loadState(source) {
	if (/^https?:/.test(source)) {
		const response = await fetch(source);
		if (!response.ok) throw new Error(`state fetch failed: HTTP ${response.status}`);
		return response.json();
	}
	return JSON.parse(await readFile(source, 'utf8'));
}

export function generate(state) {
	const lines = [
		'// generated by tools/qa/gen_master_cfg.mjs -- the QA matrix master input.',
		`// covers ${state.elements.length} elements from ${state.engine ?? 'unknown engine'}.`,
	];
	state.elements.forEach((element, i) => {
		const name = element.name;
		const alignX = ALIGN_X[i % 3];
		const alignY = ALIGN_Y[Math.floor(i / 3) % 3];
		lines.push(`hud_${name}_show 1`);
		lines.push(`hud_${name}_place screen`);
		lines.push(`hud_${name}_align_x ${alignX}`);
		lines.push(`hud_${name}_align_y ${alignY}`);
		lines.push(`hud_${name}_pos_x ${inset(alignX, i)}`);
		lines.push(`hud_${name}_pos_y ${inset(alignY, i)}`);
		if (`hud_${name}_scale` in (element.cvars ?? {})) {
			lines.push(`hud_${name}_scale 1`);
		}
		// demo_setspeed freezes demo content, not cls.realtime. Keep ping drawn
		// but stop its blink/period fields changing width between checkpoints;
		// dynamic-width judgement itself belongs to issue #42.
		if (name === 'ping') {
			lines.push('hud_ping_period 999999');
			lines.push('hud_ping_show_pl 0');
			lines.push('hud_ping_blink 0');
		}
	});
	return lines.join('\n') + '\n';
}

export function coveredElements(cfgText) {
	const names = new Set();
	for (const match of cfgText.matchAll(/^hud_(.+?)_show 1$/gm)) {
		names.add(match[1]);
	}
	return names;
}

export function checkCoverage(state, cfgText) {
	const covered = coveredElements(cfgText);
	return state.elements.map((e) => e.name).filter((name) => !covered.has(name));
}

const invokedDirectly = process.argv[1] &&
	import.meta.url === new URL(`file://${process.argv[1]}`).href;

if (invokedDirectly) {
	const [source, flag, file] = process.argv.slice(2);
	if (!source) {
		console.error('usage: gen_master_cfg.mjs <state.json|url> [--out file | --check file]');
		process.exit(2);
	}
	const state = await loadState(source);
	if (flag === '--check') {
		const missing = checkCoverage(state, await readFile(file, 'utf8'));
		if (missing.length) {
			console.error(`COVERAGE GATE: ${missing.length} registered element(s) missing from ${file}: ${missing.join(', ')}`);
			console.error('Regenerate: node tools/qa/gen_master_cfg.mjs <state> --out ' + file);
			process.exit(1);
		}
		console.log(`coverage: all ${state.elements.length} elements present in ${file}`);
	} else {
		const text = generate(state);
		const out = flag === '--out' ? file : null;
		if (out) {
			await writeFile(out, text);
			console.log(`wrote ${out} (${state.elements.length} elements)`);
		} else {
			process.stdout.write(text);
		}
	}
}
