// tools/qa/gen_master_cfg.mjs — the master input cfg, and its coverage gate.
//
//   node tools/qa/gen_master_cfg.mjs <state.json|bridge-url> [--out file]
//   node tools/qa/gen_master_cfg.mjs <state.json|bridge-url> --check <file>
//
// One cfg that touches every registered element, in deliberately stressful
// positions: alignments and offsets cycle deterministically by element index,
// every third element gets scale 2, every seventh a negative offset. The
// --check mode fails when the engine registers an element the cfg does not
// cover — coverage can never silently rot (plan B1).

import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';

const ALIGN_X = ['left', 'center', 'right'];
const ALIGN_Y = ['top', 'center', 'bottom'];

async function loadState(source) {
	if (/^https?:/.test(source)) {
		const response = await fetch(source);
		if (!response.ok) throw new Error(`state fetch failed: HTTP ${response.status}`);
		return response.json();
	}
	return JSON.parse(await readFile(source, 'utf8'));
}

export function generate(state) {
	const lines = [
		'// generated by tools/qa/gen_master_cfg.mjs -- the QA matrix master input.',
		`// covers ${state.elements.length} elements from ${state.engine ?? 'unknown engine'}.`,
	];
	state.elements.forEach((element, i) => {
		const name = element.name;
		lines.push(`hud_${name}_show 1`);
		lines.push(`hud_${name}_align_x ${ALIGN_X[i % 3]}`);
		lines.push(`hud_${name}_align_y ${ALIGN_Y[Math.floor(i / 3) % 3]}`);
		lines.push(`hud_${name}_pos_x ${i % 7 === 0 ? -8 * (1 + (i % 3)) : (i * 13) % 160}`);
		lines.push(`hud_${name}_pos_y ${(i * 29) % 120}`);
		if (`hud_${name}_scale` in (element.cvars ?? {})) {
			lines.push(`hud_${name}_scale ${i % 3 === 0 ? 2 : 1}`);
		}
	});
	return lines.join('\n') + '\n';
}

export function coveredElements(cfgText) {
	const names = new Set();
	for (const match of cfgText.matchAll(/^hud_(.+?)_show 1$/gm)) {
		names.add(match[1]);
	}
	return names;
}

export function checkCoverage(state, cfgText) {
	const covered = coveredElements(cfgText);
	return state.elements.map((e) => e.name).filter((name) => !covered.has(name));
}

const invokedDirectly = process.argv[1] &&
	import.meta.url === new URL(`file://${process.argv[1]}`).href;

if (invokedDirectly) {
	const [source, flag, file] = process.argv.slice(2);
	if (!source) {
		console.error('usage: gen_master_cfg.mjs <state.json|url> [--out file | --check file]');
		process.exit(2);
	}
	const state = await loadState(source);
	if (flag === '--check') {
		const missing = checkCoverage(state, await readFile(file, 'utf8'));
		if (missing.length) {
			console.error(`COVERAGE GATE: ${missing.length} registered element(s) missing from ${file}: ${missing.join(', ')}`);
			console.error('Regenerate: node tools/qa/gen_master_cfg.mjs <state> --out ' + file);
			process.exit(1);
		}
		console.log(`coverage: all ${state.elements.length} elements present in ${file}`);
	} else {
		const text = generate(state);
		const out = flag === '--out' ? file : null;
		if (out) {
			await writeFile(out, text);
			console.log(`wrote ${out} (${state.elements.length} elements)`);
		} else {
			process.stdout.write(text);
		}
	}
}
