// tools/fidelity/report.mjs — render a comparison into the checked-in report.
//
// The element table is generated from the comparison rows and nothing else. If
// a row is not in the measurement it is not in the table; there is no place in
// this file to type a verdict by hand, which is the point (#84 acceptance 2).
//
// The provenance block is not decoration. Every verdict below is scoped to one
// FTE artifact, one config and one demo frame, and a reader who cannot see
// which ones is being invited to over-read the result (#84 acceptance 5).

const VERDICT_MARK = {
	match: '✓',
	diverges: '✗',
	'not-assessable': '—',
	'absent-both': '·',
};

const cell = (value) => (value === undefined || value === null ? '' : String(value));

// A column of `x+0 y+0` on every matching row buries the handful that are not
// zero, which is the only thing anyone opens this table to find.
const deltaText = (row) => {
	if (!row?.delta || Object.values(row.delta).every((value) => value === 0)) return '';
	return Object.entries(row.delta)
		.map(([axis, value]) => `${axis}${value >= 0 ? '+' : ''}${value}`)
		.join(' ');
};

const rectText = (rect) => (rect ? Object.values(rect).join(',') : '');

function elementTable(result) {
	const byElement = new Map();
	for (const row of result.measured) {
		if (!byElement.has(row.element)) byElement.set(row.element, {});
		byElement.get(row.element)[row.dimension] = row;
	}
	const lines = [
		'| element | presence | position | size | reference | preview | delta |',
		'|---|---|---|---|---|---|---|',
	];
	for (const [element, rows] of byElement) {
		const geometry = [deltaText(rows.position), deltaText(rows.size)].filter(Boolean).join(' · ');
		const side = (which) => (rows.position?.[which]
			? `${rectText(rows.position[which])} ${rectText(rows.size[which])}`
			: '');
		const columns = [
			element,
			`${VERDICT_MARK[rows.presence.verdict]} ${rows.presence.code}`,
			VERDICT_MARK[rows.position.verdict],
			VERDICT_MARK[rows.size.verdict],
			side('reference'),
			side('preview'),
			geometry,
		];
		lines.push(`| ${columns.map(cell).join(' | ')} |`);
	}
	return lines.join('\n');
}

function claimsTable(carried) {
	if (!carried.length) return '_No carried claims._';
	const lines = [
		'| element | dimension | verdict | claim | source | observed |',
		'|---|---|---|---|---|---|',
	];
	for (const claim of carried) {
		lines.push(`| ${claim.element} | ${claim.dimension} | ${claim.verdict} | ${claim.claim} | ${claim.source} | ${claim.observed} |`);
	}
	return lines.join('\n');
}

function provenanceTable(provenance) {
	const lines = ['| input | value |', '|---|---|'];
	for (const [key, value] of Object.entries(provenance)) {
		lines.push(`| ${key} | ${cell(value)} |`);
	}
	return lines.join('\n');
}

/**
 * @param {object} result     compareStates() output
 * @param {Array}  carried    carryClaims() output
 * @param {object} provenance every input that scopes the verdicts
 * @param {string} date       ISO date, passed in so the renderer stays pure
 */
export function renderReport({ result, carried = [], provenance = {}, date }) {
	const scope = [
		'## Scope of this measurement',
		'',
		'Every verdict above is scoped to exactly the inputs in the provenance table:',
		'one FTE artifact, one ezQuake build, one config, one demo frozen at one point,',
		'at one console size. It says nothing about any other config, any other demo',
		'frame, or any other build of either engine. A divergence absent here has not',
		'been shown not to exist — it has been shown not to occur under these inputs.',
		'',
		'`texture` and `colour` are not measured. Comparing pixels across two different',
		'renderers is not a verdict this run can make honestly, so those dimensions are',
		'carried as dated, sourced claims and go stale on their own when the element',
		'they describe stops being drawn.',
		'',
		'**The run cannot prove the two engines sit on the same demo frame.** Neither',
		'bridge reports a demo time, so what is established is weaker: both engines were',
		'frozen (the provenance table records each one\'s demo speed) and two consecutive',
		'reads judged identically. Elements whose size tracks their content — score and',
		'frag digits, ping, item timers — can therefore differ by a frame\'s worth of game',
		'state rather than by a real fidelity gap. Read a `size` divergence on a',
		'content-derived element as a question, not a verdict.',
	].join('\n');

	const header = result.comparable
		? `**${result.counts.diverging} diverging** · ${result.counts.matching} matching · ` +
			`${result.counts.not_assessable} not assessable · ${result.counts.absent_both} drawn by neither ` +
			`· ${result.counts.elements} elements · tolerance ${result.tolerance_px}px`
		: `**Not comparable.** ${result.incomparable_reason}`;

	return [
		`# FTE-web preview vs ezQuake — fidelity report ${date}`,
		'',
		'Generated by `tools/fidelity/run.sh`. Do not edit by hand; edits are',
		'overwritten by the next run and the table below is produced from the',
		'measurement, not typed.',
		'',
		header,
		'',
		'## Provenance',
		'',
		provenanceTable(provenance),
		'',
		'## Elements',
		'',
		result.comparable ? elementTable(result) : '_No element table: the two snapshots were not comparable._',
		'',
		'## Carried claims — asserted, not measured',
		'',
		claimsTable(carried),
		'',
		scope,
		'',
	].join('\n');
}
